name: Publish Docker image to GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image 🥳
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 💡 Adicionando plataformas para aproveitar o Buildx e QEMU
          platforms: linux/amd64,linux/arm64
          tags:
            - ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.sha }}
            - ghcr.io/${{ github.repository_owner }}/cicd-lab:latest

      - name: Show published image
        run: echo Imagem publicada: ghcr.io/${{ github.repository_owner }}/cicd-lab:${{ github.sha }}